// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAup2HTMXObKZbMqec9coXsw3y4PkKOeZU',
    appId: '1:960140212069:web:b2dcfdf496f6c6f1dc538c',
    messagingSenderId: '960140212069',
    projectId: 'discount-project-6dfc5',
    authDomain: 'discount-project-6dfc5.firebaseapp.com',
    storageBucket: 'discount-project-6dfc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgl5EuSEHtVFBGiDYyFaRsix2fNHa45ck',
    appId: '1:960140212069:android:e81f298fcf63bef4dc538c',
    messagingSenderId: '960140212069',
    projectId: 'discount-project-6dfc5',
    storageBucket: 'discount-project-6dfc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAGJ92B3iOl_v-e3K73hDWpID7dCaPKNI',
    appId: '1:960140212069:ios:f08f20f29d4c5ef3dc538c',
    messagingSenderId: '960140212069',
    projectId: 'discount-project-6dfc5',
    storageBucket: 'discount-project-6dfc5.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAGJ92B3iOl_v-e3K73hDWpID7dCaPKNI',
    appId: '1:960140212069:ios:8000ffc26b600a35dc538c',
    messagingSenderId: '960140212069',
    projectId: 'discount-project-6dfc5',
    storageBucket: 'discount-project-6dfc5.appspot.com',
    iosBundleId: 'com.example.mobile.RunnerTests',
  );
}
